// Schema for the on-disk cache record produced by sloff per (spec, task, input_hash) tuple.
//
// SSoT for ADR-0009. Wire-incompatible changes require bumping the package
// version (sloff.cache.v2). See
// ../../../../docs/adr/0009-cache-record-binary-serialization.md.
//
// Design rules enforced here:
//   - No `map<,>` fields. Order-sensitive collections are `repeated <Entry>`
//     and the marshaller sorts deterministically before writing.
//   - schema_version is a closed enum so unknown / invalid versions cannot be
//     represented at the wire level.
//   - Sub-messages are top-level; the `sloff.cache.v1` package qualifier
//     keeps names like Spec / Input / Output appropriately scoped.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sloff/cache/v1/cache.proto

package cachev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaVersion enumerates the schemas a Record may carry. Enum values match
// the on-disk version number. The YAML format used schema_version 1 before
// ADR-0009 and is intentionally absent here.
type SchemaVersion int32

const (
	SchemaVersion_SCHEMA_VERSION_UNSPECIFIED SchemaVersion = 0
	// First protobuf-encoded schema. Introduced by ADR-0009. Superseded by V3
	// and intentionally retained as a closed enum value so legacy on-disk
	// records can be detected and rejected explicitly.
	SchemaVersion_SCHEMA_VERSION_V2 SchemaVersion = 2
	// Drops Record.generated_at; the filename's timestamp prefix replaces it
	// (ADR-0010).
	SchemaVersion_SCHEMA_VERSION_V3 SchemaVersion = 3
)

// Enum value maps for SchemaVersion.
var (
	SchemaVersion_name = map[int32]string{
		0: "SCHEMA_VERSION_UNSPECIFIED",
		2: "SCHEMA_VERSION_V2",
		3: "SCHEMA_VERSION_V3",
	}
	SchemaVersion_value = map[string]int32{
		"SCHEMA_VERSION_UNSPECIFIED": 0,
		"SCHEMA_VERSION_V2":          2,
		"SCHEMA_VERSION_V3":          3,
	}
)

func (x SchemaVersion) Enum() *SchemaVersion {
	p := new(SchemaVersion)
	*p = x
	return p
}

func (x SchemaVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_sloff_cache_v1_cache_proto_enumTypes[0].Descriptor()
}

func (SchemaVersion) Type() protoreflect.EnumType {
	return &file_sloff_cache_v1_cache_proto_enumTypes[0]
}

func (x SchemaVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaVersion.Descriptor instead.
func (SchemaVersion) EnumDescriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

// Record is one cache entry on disk. Lives at
// .sloff/cache/<spec_relpath>/<task_id>/<YYYYMMDDHHMMSSsss>-<input_hash>.pb.
// The filename's timestamp prefix encodes the record's initial creation time
// (ADR-0010); no wall-clock field is carried in the wire format so that the
// bytes are a deterministic function of the input.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion SchemaVersion          `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,enum=sloff.cache.v1.SchemaVersion" json:"schema_version,omitempty"`
	Spec          *Spec                  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Input         *Input                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        *Output                `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetSchemaVersion() SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return SchemaVersion_SCHEMA_VERSION_UNSPECIFIED
}

func (x *Record) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Record) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Record) GetOutput() *Output {
	if x != nil {
		return x.Output
	}
	return nil
}

type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{1}
}

func (x *Spec) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Spec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Spec) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

// Input captures everything that contributes to the cache key for one task.
// hash = sha256_concat(files_hash, cmd_hash, resolved_versions_hash).
type Input struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hash      string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	FilesHash string                 `protobuf:"bytes,2,opt,name=files_hash,json=filesHash,proto3" json:"files_hash,omitempty"`
	CmdHash   string                 `protobuf:"bytes,3,opt,name=cmd_hash,json=cmdHash,proto3" json:"cmd_hash,omitempty"`
	// Equals the sorted-concat-and-SHA256 of resolved_versions[*].version.
	// Replaces the previous "tools_hash" field. The term "tool" was inaccurate
	// because go-local and pnpm-local resolvers contribute transitive external
	// dependency pins through this same path, not just user-declared tools.
	ResolvedVersionsHash string `protobuf:"bytes,4,opt,name=resolved_versions_hash,json=resolvedVersionsHash,proto3" json:"resolved_versions_hash,omitempty"`
	// Per-entry detail of every logical version pin contributing to
	// resolved_versions_hash. Unifies what previous YAML schema kept in
	// input.components.tools_hash plus the parallel generator_version_snapshot.
	// Sorted by name ascending before marshal.
	ResolvedVersions []*ResolvedVersion `protobuf:"bytes,5,rep,name=resolved_versions,json=resolvedVersions,proto3" json:"resolved_versions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Input) GetFilesHash() string {
	if x != nil {
		return x.FilesHash
	}
	return ""
}

func (x *Input) GetCmdHash() string {
	if x != nil {
		return x.CmdHash
	}
	return ""
}

func (x *Input) GetResolvedVersionsHash() string {
	if x != nil {
		return x.ResolvedVersionsHash
	}
	return ""
}

func (x *Input) GetResolvedVersions() []*ResolvedVersion {
	if x != nil {
		return x.ResolvedVersions
	}
	return nil
}

type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hash  string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Sorted by path ascending before marshal.
	Files         []*FileEntry `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{3}
}

func (x *Output) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Output) GetFiles() []*FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repo-root relative, slash-separated.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// SHA-256 hex.
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{4}
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ResolvedVersion is one OS-neutral logical version pin returned by a
// Resolver. Covers user-declared tools (script resolver), transitive Go
// module pins (go-local), and transitive npm package pins (pnpm-local).
type ResolvedVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Logical version string fed into Input.resolved_versions_hash.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Informational source identifier (e.g. "<bin> --version", "go.mod",
	// "pnpm-local:@org/my-codegen"). Not part of the hash.
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedVersion) Reset() {
	*x = ResolvedVersion{}
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedVersion) ProtoMessage() {}

func (x *ResolvedVersion) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_cache_v1_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedVersion.ProtoReflect.Descriptor instead.
func (*ResolvedVersion) Descriptor() ([]byte, []int) {
	return file_sloff_cache_v1_cache_proto_rawDescGZIP(), []int{5}
}

func (x *ResolvedVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolvedVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolvedVersion) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_sloff_cache_v1_cache_proto protoreflect.FileDescriptor

const file_sloff_cache_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x1asloff/cache/v1/cache.proto\x12\x0esloff.cache.v1\"\xe9\x01\n" +
	"\x06Record\x12D\n" +
	"\x0eschema_version\x18\x01 \x01(\x0e2\x1d.sloff.cache.v1.SchemaVersionR\rschemaVersion\x12(\n" +
	"\x04spec\x18\x02 \x01(\v2\x14.sloff.cache.v1.SpecR\x04spec\x12+\n" +
	"\x05input\x18\x03 \x01(\v2\x15.sloff.cache.v1.InputR\x05input\x12.\n" +
	"\x06output\x18\x04 \x01(\v2\x16.sloff.cache.v1.OutputR\x06outputJ\x04\b\x05\x10\x06R\fgenerated_at\"C\n" +
	"\x04Spec\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\"\xd9\x01\n" +
	"\x05Input\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"files_hash\x18\x02 \x01(\tR\tfilesHash\x12\x19\n" +
	"\bcmd_hash\x18\x03 \x01(\tR\acmdHash\x124\n" +
	"\x16resolved_versions_hash\x18\x04 \x01(\tR\x14resolvedVersionsHash\x12L\n" +
	"\x11resolved_versions\x18\x05 \x03(\v2\x1f.sloff.cache.v1.ResolvedVersionR\x10resolvedVersions\"M\n" +
	"\x06Output\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12/\n" +
	"\x05files\x18\x02 \x03(\v2\x19.sloff.cache.v1.FileEntryR\x05files\"3\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"W\n" +
	"\x0fResolvedVersion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source*]\n" +
	"\rSchemaVersion\x12\x1e\n" +
	"\x1aSCHEMA_VERSION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SCHEMA_VERSION_V2\x10\x02\x12\x15\n" +
	"\x11SCHEMA_VERSION_V3\x10\x03B\xbd\x01\n" +
	"\x12com.sloff.cache.v1B\n" +
	"CacheProtoP\x01ZAgithub.com/izumin5210/sloff/internal/proto/sloff/cache/v1;cachev1\xa2\x02\x03SCX\xaa\x02\x0eSloff.Cache.V1\xca\x02\x0eSloff\\Cache\\V1\xe2\x02\x1aSloff\\Cache\\V1\\GPBMetadata\xea\x02\x10Sloff::Cache::V1b\x06proto3"

var (
	file_sloff_cache_v1_cache_proto_rawDescOnce sync.Once
	file_sloff_cache_v1_cache_proto_rawDescData []byte
)

func file_sloff_cache_v1_cache_proto_rawDescGZIP() []byte {
	file_sloff_cache_v1_cache_proto_rawDescOnce.Do(func() {
		file_sloff_cache_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sloff_cache_v1_cache_proto_rawDesc), len(file_sloff_cache_v1_cache_proto_rawDesc)))
	})
	return file_sloff_cache_v1_cache_proto_rawDescData
}

var file_sloff_cache_v1_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sloff_cache_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sloff_cache_v1_cache_proto_goTypes = []any{
	(SchemaVersion)(0),      // 0: sloff.cache.v1.SchemaVersion
	(*Record)(nil),          // 1: sloff.cache.v1.Record
	(*Spec)(nil),            // 2: sloff.cache.v1.Spec
	(*Input)(nil),           // 3: sloff.cache.v1.Input
	(*Output)(nil),          // 4: sloff.cache.v1.Output
	(*FileEntry)(nil),       // 5: sloff.cache.v1.FileEntry
	(*ResolvedVersion)(nil), // 6: sloff.cache.v1.ResolvedVersion
}
var file_sloff_cache_v1_cache_proto_depIdxs = []int32{
	0, // 0: sloff.cache.v1.Record.schema_version:type_name -> sloff.cache.v1.SchemaVersion
	2, // 1: sloff.cache.v1.Record.spec:type_name -> sloff.cache.v1.Spec
	3, // 2: sloff.cache.v1.Record.input:type_name -> sloff.cache.v1.Input
	4, // 3: sloff.cache.v1.Record.output:type_name -> sloff.cache.v1.Output
	6, // 4: sloff.cache.v1.Input.resolved_versions:type_name -> sloff.cache.v1.ResolvedVersion
	5, // 5: sloff.cache.v1.Output.files:type_name -> sloff.cache.v1.FileEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sloff_cache_v1_cache_proto_init() }
func file_sloff_cache_v1_cache_proto_init() {
	if File_sloff_cache_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sloff_cache_v1_cache_proto_rawDesc), len(file_sloff_cache_v1_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sloff_cache_v1_cache_proto_goTypes,
		DependencyIndexes: file_sloff_cache_v1_cache_proto_depIdxs,
		EnumInfos:         file_sloff_cache_v1_cache_proto_enumTypes,
		MessageInfos:      file_sloff_cache_v1_cache_proto_msgTypes,
	}.Build()
	File_sloff_cache_v1_cache_proto = out.File
	file_sloff_cache_v1_cache_proto_goTypes = nil
	file_sloff_cache_v1_cache_proto_depIdxs = nil
}
