# yaml-language-server: $schema=https://github.com/evilmartians/lefthook/raw/refs/tags/v2.1.6/schema.json

pre-commit:
  commands:
    format:
      glob: "*.go"
      exclude:
        - "*.pb.go"
      run: |
        go tool gofumpt -w -- {staged_files}
      stage_fixed: true
