// Schema for the host-local per-file content-digest cache (ADR-0014).
//
// Unlike the fingerprint Record, this cache is NOT content-addressed: it is a
// per-machine acceleration cache keyed by absolute file path and is safe to
// delete at any time. Byte stability is therefore not a correctness
// requirement, but entries are still sorted by path and marshalled
// deterministically (proto.MarshalOptions{Deterministic: true}) so the on-disk
// file is reproducible and easy to diff while debugging.
//
// The serialization mirrors the fingerprint record (ADR-0009): protobuf with a
// closed schema_version enum, no `map<,>` fields. See
// ../../../../docs/adr/0014-persistent-file-content-hash-cache.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sloff/filecache/v1/filecache.proto

package filecachev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaVersion is a closed enum so an incompatible on-disk cache is rejected
// wholesale (read as cold) instead of returning incompatible digests. Bump it
// whenever the on-disk schema OR the digest composition changes.
type SchemaVersion int32

const (
	SchemaVersion_SCHEMA_VERSION_UNSPECIFIED SchemaVersion = 0
	// First schema. Entry identity = (size, mtime, ctime, inode).
	SchemaVersion_SCHEMA_VERSION_V1 SchemaVersion = 1
)

// Enum value maps for SchemaVersion.
var (
	SchemaVersion_name = map[int32]string{
		0: "SCHEMA_VERSION_UNSPECIFIED",
		1: "SCHEMA_VERSION_V1",
	}
	SchemaVersion_value = map[string]int32{
		"SCHEMA_VERSION_UNSPECIFIED": 0,
		"SCHEMA_VERSION_V1":          1,
	}
)

func (x SchemaVersion) Enum() *SchemaVersion {
	p := new(SchemaVersion)
	*p = x
	return p
}

func (x SchemaVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_sloff_filecache_v1_filecache_proto_enumTypes[0].Descriptor()
}

func (SchemaVersion) Type() protoreflect.EnumType {
	return &file_sloff_filecache_v1_filecache_proto_enumTypes[0]
}

func (x SchemaVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaVersion.Descriptor instead.
func (SchemaVersion) EnumDescriptor() ([]byte, []int) {
	return file_sloff_filecache_v1_filecache_proto_rawDescGZIP(), []int{0}
}

// Cache is the whole on-disk file at <cache_root>/filehashes.pb. A missing,
// unreadable, or schema-mismatched file is treated as an empty (cold) cache —
// never an error — so a first run or a format bump simply rehashes.
type Cache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion SchemaVersion          `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,enum=sloff.filecache.v1.SchemaVersion" json:"schema_version,omitempty"`
	// One entry per cached file. Sorted by path ascending before marshal.
	Entries       []*Entry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cache) Reset() {
	*x = Cache{}
	mi := &file_sloff_filecache_v1_filecache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cache) ProtoMessage() {}

func (x *Cache) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_filecache_v1_filecache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cache.ProtoReflect.Descriptor instead.
func (*Cache) Descriptor() ([]byte, []int) {
	return file_sloff_filecache_v1_filecache_proto_rawDescGZIP(), []int{0}
}

func (x *Cache) GetSchemaVersion() SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return SchemaVersion_SCHEMA_VERSION_UNSPECIFIED
}

func (x *Cache) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Entry caches one file's content digest under its file identity. A cached
// digest is reused only when the live stat still matches size + mtime (and
// ctime + inode when identity_ok). See ADR-0014.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute (root-joined) filesystem path.
	Path       string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size       int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MtimeNanos int64  `protobuf:"varint,3,opt,name=mtime_nanos,json=mtimeNanos,proto3" json:"mtime_nanos,omitempty"`
	// Inode-change time, unix nanos; 0 when the platform has no ctime.
	CtimeNanos int64 `protobuf:"varint,4,opt,name=ctime_nanos,json=ctimeNanos,proto3" json:"ctime_nanos,omitempty"`
	// 0 when the platform has no inode.
	Inode uint64 `protobuf:"varint,5,opt,name=inode,proto3" json:"inode,omitempty"`
	// Whether ctime_nanos + inode are meaningful for this entry. When false the
	// cache degrades to (size, mtime) for this entry.
	IdentityOk bool `protobuf:"varint,6,opt,name=identity_ok,json=identityOk,proto3" json:"identity_ok,omitempty"`
	// Raw SHA-256 content digest (32 bytes).
	Digest        []byte `protobuf:"bytes,7,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_sloff_filecache_v1_filecache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_filecache_v1_filecache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_sloff_filecache_v1_filecache_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Entry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Entry) GetMtimeNanos() int64 {
	if x != nil {
		return x.MtimeNanos
	}
	return 0
}

func (x *Entry) GetCtimeNanos() int64 {
	if x != nil {
		return x.CtimeNanos
	}
	return 0
}

func (x *Entry) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Entry) GetIdentityOk() bool {
	if x != nil {
		return x.IdentityOk
	}
	return false
}

func (x *Entry) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

var File_sloff_filecache_v1_filecache_proto protoreflect.FileDescriptor

const file_sloff_filecache_v1_filecache_proto_rawDesc = "" +
	"\n" +
	"\"sloff/filecache/v1/filecache.proto\x12\x12sloff.filecache.v1\"\x86\x01\n" +
	"\x05Cache\x12H\n" +
	"\x0eschema_version\x18\x01 \x01(\x0e2!.sloff.filecache.v1.SchemaVersionR\rschemaVersion\x123\n" +
	"\aentries\x18\x02 \x03(\v2\x19.sloff.filecache.v1.EntryR\aentries\"\xc0\x01\n" +
	"\x05Entry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1f\n" +
	"\vmtime_nanos\x18\x03 \x01(\x03R\n" +
	"mtimeNanos\x12\x1f\n" +
	"\vctime_nanos\x18\x04 \x01(\x03R\n" +
	"ctimeNanos\x12\x14\n" +
	"\x05inode\x18\x05 \x01(\x04R\x05inode\x12\x1f\n" +
	"\videntity_ok\x18\x06 \x01(\bR\n" +
	"identityOk\x12\x16\n" +
	"\x06digest\x18\a \x01(\fR\x06digest*F\n" +
	"\rSchemaVersion\x12\x1e\n" +
	"\x1aSCHEMA_VERSION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SCHEMA_VERSION_V1\x10\x01B\xdd\x01\n" +
	"\x16com.sloff.filecache.v1B\x0eFilecacheProtoP\x01ZIgithub.com/izumin5210/sloff/internal/proto/sloff/filecache/v1;filecachev1\xa2\x02\x03SFX\xaa\x02\x12Sloff.Filecache.V1\xca\x02\x12Sloff\\Filecache\\V1\xe2\x02\x1eSloff\\Filecache\\V1\\GPBMetadata\xea\x02\x14Sloff::Filecache::V1b\x06proto3"

var (
	file_sloff_filecache_v1_filecache_proto_rawDescOnce sync.Once
	file_sloff_filecache_v1_filecache_proto_rawDescData []byte
)

func file_sloff_filecache_v1_filecache_proto_rawDescGZIP() []byte {
	file_sloff_filecache_v1_filecache_proto_rawDescOnce.Do(func() {
		file_sloff_filecache_v1_filecache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sloff_filecache_v1_filecache_proto_rawDesc), len(file_sloff_filecache_v1_filecache_proto_rawDesc)))
	})
	return file_sloff_filecache_v1_filecache_proto_rawDescData
}

var file_sloff_filecache_v1_filecache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sloff_filecache_v1_filecache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sloff_filecache_v1_filecache_proto_goTypes = []any{
	(SchemaVersion)(0), // 0: sloff.filecache.v1.SchemaVersion
	(*Cache)(nil),      // 1: sloff.filecache.v1.Cache
	(*Entry)(nil),      // 2: sloff.filecache.v1.Entry
}
var file_sloff_filecache_v1_filecache_proto_depIdxs = []int32{
	0, // 0: sloff.filecache.v1.Cache.schema_version:type_name -> sloff.filecache.v1.SchemaVersion
	2, // 1: sloff.filecache.v1.Cache.entries:type_name -> sloff.filecache.v1.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sloff_filecache_v1_filecache_proto_init() }
func file_sloff_filecache_v1_filecache_proto_init() {
	if File_sloff_filecache_v1_filecache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sloff_filecache_v1_filecache_proto_rawDesc), len(file_sloff_filecache_v1_filecache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sloff_filecache_v1_filecache_proto_goTypes,
		DependencyIndexes: file_sloff_filecache_v1_filecache_proto_depIdxs,
		EnumInfos:         file_sloff_filecache_v1_filecache_proto_enumTypes,
		MessageInfos:      file_sloff_filecache_v1_filecache_proto_msgTypes,
	}.Build()
	File_sloff_filecache_v1_filecache_proto = out.File
	file_sloff_filecache_v1_filecache_proto_goTypes = nil
	file_sloff_filecache_v1_filecache_proto_depIdxs = nil
}
