// Schema for the on-disk cache record produced by sloff per (spec, task, input_hash) tuple.
//
// SSoT for ADR-0009. Wire-incompatible changes require bumping the package version
// (sloff.v2). See ../../../docs/adr/0009-cache-record-binary-serialization.md.
//
// Design rules enforced here:
//   - No `map<,>` fields. Order-sensitive collections are `repeated <Entry>` and the
//     marshaller sorts deterministically before writing.
//   - schema_version is a closed enum so unknown / invalid versions cannot be
//     represented at the wire level.
//   - Sub-messages are nested under CacheRecord to avoid leaking broad names
//     (Spec / Input / Output) at the package level.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sloff/v1/cache.proto

package sloffv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchemaVersion enumerates the schemas a CacheRecord may carry.
// Enum values match the on-disk version number. The YAML format used
// schema_version 1 before ADR-0009 and is intentionally absent here.
type CacheRecord_SchemaVersion int32

const (
	CacheRecord_SCHEMA_VERSION_UNSPECIFIED CacheRecord_SchemaVersion = 0
	// First protobuf-encoded schema. Introduced by ADR-0009.
	CacheRecord_SCHEMA_VERSION_V2 CacheRecord_SchemaVersion = 2
)

// Enum value maps for CacheRecord_SchemaVersion.
var (
	CacheRecord_SchemaVersion_name = map[int32]string{
		0: "SCHEMA_VERSION_UNSPECIFIED",
		2: "SCHEMA_VERSION_V2",
	}
	CacheRecord_SchemaVersion_value = map[string]int32{
		"SCHEMA_VERSION_UNSPECIFIED": 0,
		"SCHEMA_VERSION_V2":          2,
	}
)

func (x CacheRecord_SchemaVersion) Enum() *CacheRecord_SchemaVersion {
	p := new(CacheRecord_SchemaVersion)
	*p = x
	return p
}

func (x CacheRecord_SchemaVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheRecord_SchemaVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_sloff_v1_cache_proto_enumTypes[0].Descriptor()
}

func (CacheRecord_SchemaVersion) Type() protoreflect.EnumType {
	return &file_sloff_v1_cache_proto_enumTypes[0]
}

func (x CacheRecord_SchemaVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheRecord_SchemaVersion.Descriptor instead.
func (CacheRecord_SchemaVersion) EnumDescriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0, 0}
}

// CacheRecord is one cache entry on disk. Lives at
// .sloff/cache/<spec_relpath>/<task_id>/<input_hash>.pb.
type CacheRecord struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	SchemaVersion CacheRecord_SchemaVersion `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3,enum=sloff.v1.CacheRecord_SchemaVersion" json:"schema_version,omitempty"`
	Spec          *CacheRecord_Spec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Input         *CacheRecord_Input        `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        *CacheRecord_Output       `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	// Informational. Not part of cache identity. Drift alone does not trigger
	// a write per ADR-0009 §"byte stability の担保".
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRecord) Reset() {
	*x = CacheRecord{}
	mi := &file_sloff_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord) ProtoMessage() {}

func (x *CacheRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord.ProtoReflect.Descriptor instead.
func (*CacheRecord) Descriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheRecord) GetSchemaVersion() CacheRecord_SchemaVersion {
	if x != nil {
		return x.SchemaVersion
	}
	return CacheRecord_SCHEMA_VERSION_UNSPECIFIED
}

func (x *CacheRecord) GetSpec() *CacheRecord_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CacheRecord) GetInput() *CacheRecord_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CacheRecord) GetOutput() *CacheRecord_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CacheRecord) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type CacheRecord_Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRecord_Spec) Reset() {
	*x = CacheRecord_Spec{}
	mi := &file_sloff_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord_Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord_Spec) ProtoMessage() {}

func (x *CacheRecord_Spec) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord_Spec.ProtoReflect.Descriptor instead.
func (*CacheRecord_Spec) Descriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CacheRecord_Spec) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *CacheRecord_Spec) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CacheRecord_Spec) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

// Input captures everything that contributes to the cache key for one task.
// hash = sha256_concat(files_hash, cmd_hash, resolved_versions_hash).
type CacheRecord_Input struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hash      string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	FilesHash string                 `protobuf:"bytes,2,opt,name=files_hash,json=filesHash,proto3" json:"files_hash,omitempty"`
	CmdHash   string                 `protobuf:"bytes,3,opt,name=cmd_hash,json=cmdHash,proto3" json:"cmd_hash,omitempty"`
	// Equals the sorted-concat-and-SHA256 of resolved_versions[*].version.
	// Replaces the previous "tools_hash" field. The term "tool" was inaccurate
	// because go-local and pnpm-local resolvers contribute transitive external
	// dependency pins through this same path, not just user-declared tools.
	ResolvedVersionsHash string `protobuf:"bytes,4,opt,name=resolved_versions_hash,json=resolvedVersionsHash,proto3" json:"resolved_versions_hash,omitempty"`
	// Per-entry detail of every logical version pin contributing to
	// resolved_versions_hash. Unifies what was previously split between the
	// hash side ("tools_hash" inputs) and the informational side
	// ("generator_version_snapshot"). Sorted by name ascending before marshal.
	ResolvedVersions []*CacheRecord_Input_ResolvedVersion `protobuf:"bytes,5,rep,name=resolved_versions,json=resolvedVersions,proto3" json:"resolved_versions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CacheRecord_Input) Reset() {
	*x = CacheRecord_Input{}
	mi := &file_sloff_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord_Input) ProtoMessage() {}

func (x *CacheRecord_Input) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord_Input.ProtoReflect.Descriptor instead.
func (*CacheRecord_Input) Descriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CacheRecord_Input) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CacheRecord_Input) GetFilesHash() string {
	if x != nil {
		return x.FilesHash
	}
	return ""
}

func (x *CacheRecord_Input) GetCmdHash() string {
	if x != nil {
		return x.CmdHash
	}
	return ""
}

func (x *CacheRecord_Input) GetResolvedVersionsHash() string {
	if x != nil {
		return x.ResolvedVersionsHash
	}
	return ""
}

func (x *CacheRecord_Input) GetResolvedVersions() []*CacheRecord_Input_ResolvedVersion {
	if x != nil {
		return x.ResolvedVersions
	}
	return nil
}

type CacheRecord_Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hash  string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Sorted by path ascending before marshal.
	Files         []*CacheRecord_FileEntry `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRecord_Output) Reset() {
	*x = CacheRecord_Output{}
	mi := &file_sloff_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord_Output) ProtoMessage() {}

func (x *CacheRecord_Output) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord_Output.ProtoReflect.Descriptor instead.
func (*CacheRecord_Output) Descriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CacheRecord_Output) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *CacheRecord_Output) GetFiles() []*CacheRecord_FileEntry {
	if x != nil {
		return x.Files
	}
	return nil
}

type CacheRecord_FileEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repo-root relative, slash-separated.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// SHA-256 hex.
	Hash          string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRecord_FileEntry) Reset() {
	*x = CacheRecord_FileEntry{}
	mi := &file_sloff_v1_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord_FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord_FileEntry) ProtoMessage() {}

func (x *CacheRecord_FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_v1_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord_FileEntry.ProtoReflect.Descriptor instead.
func (*CacheRecord_FileEntry) Descriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0, 3}
}

func (x *CacheRecord_FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CacheRecord_FileEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ResolvedVersion is one OS-neutral logical version pin returned by a
// Resolver. Covers user-declared tools (script resolver), transitive Go
// module pins (go-local), and transitive npm package pins (pnpm-local).
type CacheRecord_Input_ResolvedVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Logical version string fed into resolved_versions_hash.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Informational source identifier (e.g. "<bin> --version", "go.mod",
	// "pnpm-local:@org/my-codegen"). Not part of the hash.
	Source        string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRecord_Input_ResolvedVersion) Reset() {
	*x = CacheRecord_Input_ResolvedVersion{}
	mi := &file_sloff_v1_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRecord_Input_ResolvedVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRecord_Input_ResolvedVersion) ProtoMessage() {}

func (x *CacheRecord_Input_ResolvedVersion) ProtoReflect() protoreflect.Message {
	mi := &file_sloff_v1_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRecord_Input_ResolvedVersion.ProtoReflect.Descriptor instead.
func (*CacheRecord_Input_ResolvedVersion) Descriptor() ([]byte, []int) {
	return file_sloff_v1_cache_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *CacheRecord_Input_ResolvedVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheRecord_Input_ResolvedVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CacheRecord_Input_ResolvedVersion) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

var File_sloff_v1_cache_proto protoreflect.FileDescriptor

const file_sloff_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x14sloff/v1/cache.proto\x12\bsloff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\a\n" +
	"\vCacheRecord\x12J\n" +
	"\x0eschema_version\x18\x01 \x01(\x0e2#.sloff.v1.CacheRecord.SchemaVersionR\rschemaVersion\x12.\n" +
	"\x04spec\x18\x02 \x01(\v2\x1a.sloff.v1.CacheRecord.SpecR\x04spec\x121\n" +
	"\x05input\x18\x03 \x01(\v2\x1b.sloff.v1.CacheRecord.InputR\x05input\x124\n" +
	"\x06output\x18\x04 \x01(\v2\x1c.sloff.v1.CacheRecord.OutputR\x06output\x12=\n" +
	"\fgenerated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x1aC\n" +
	"\x04Spec\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\tR\x03cmd\x1a\xbe\x02\n" +
	"\x05Input\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x1d\n" +
	"\n" +
	"files_hash\x18\x02 \x01(\tR\tfilesHash\x12\x19\n" +
	"\bcmd_hash\x18\x03 \x01(\tR\acmdHash\x124\n" +
	"\x16resolved_versions_hash\x18\x04 \x01(\tR\x14resolvedVersionsHash\x12X\n" +
	"\x11resolved_versions\x18\x05 \x03(\v2+.sloff.v1.CacheRecord.Input.ResolvedVersionR\x10resolvedVersions\x1aW\n" +
	"\x0fResolvedVersion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x1aS\n" +
	"\x06Output\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x125\n" +
	"\x05files\x18\x02 \x03(\v2\x1f.sloff.v1.CacheRecord.FileEntryR\x05files\x1a3\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"F\n" +
	"\rSchemaVersion\x12\x1e\n" +
	"\x1aSCHEMA_VERSION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SCHEMA_VERSION_V2\x10\x02B\x98\x01\n" +
	"\fcom.sloff.v1B\n" +
	"CacheProtoP\x01Z;github.com/izumin5210/sloff/internal/proto/sloff/v1;sloffv1\xa2\x02\x03SXX\xaa\x02\bSloff.V1\xca\x02\bSloff\\V1\xe2\x02\x14Sloff\\V1\\GPBMetadata\xea\x02\tSloff::V1b\x06proto3"

var (
	file_sloff_v1_cache_proto_rawDescOnce sync.Once
	file_sloff_v1_cache_proto_rawDescData []byte
)

func file_sloff_v1_cache_proto_rawDescGZIP() []byte {
	file_sloff_v1_cache_proto_rawDescOnce.Do(func() {
		file_sloff_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sloff_v1_cache_proto_rawDesc), len(file_sloff_v1_cache_proto_rawDesc)))
	})
	return file_sloff_v1_cache_proto_rawDescData
}

var (
	file_sloff_v1_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_sloff_v1_cache_proto_msgTypes  = make([]protoimpl.MessageInfo, 6)
	file_sloff_v1_cache_proto_goTypes   = []any{
		CacheRecord_SchemaVersion(0),              // 0: sloff.v1.CacheRecord.SchemaVersion
		(*CacheRecord)(nil),                       // 1: sloff.v1.CacheRecord
		(*CacheRecord_Spec)(nil),                  // 2: sloff.v1.CacheRecord.Spec
		(*CacheRecord_Input)(nil),                 // 3: sloff.v1.CacheRecord.Input
		(*CacheRecord_Output)(nil),                // 4: sloff.v1.CacheRecord.Output
		(*CacheRecord_FileEntry)(nil),             // 5: sloff.v1.CacheRecord.FileEntry
		(*CacheRecord_Input_ResolvedVersion)(nil), // 6: sloff.v1.CacheRecord.Input.ResolvedVersion
		(*timestamppb.Timestamp)(nil),             // 7: google.protobuf.Timestamp
	}
)
var file_sloff_v1_cache_proto_depIdxs = []int32{
	0, // 0: sloff.v1.CacheRecord.schema_version:type_name -> sloff.v1.CacheRecord.SchemaVersion
	2, // 1: sloff.v1.CacheRecord.spec:type_name -> sloff.v1.CacheRecord.Spec
	3, // 2: sloff.v1.CacheRecord.input:type_name -> sloff.v1.CacheRecord.Input
	4, // 3: sloff.v1.CacheRecord.output:type_name -> sloff.v1.CacheRecord.Output
	7, // 4: sloff.v1.CacheRecord.generated_at:type_name -> google.protobuf.Timestamp
	6, // 5: sloff.v1.CacheRecord.Input.resolved_versions:type_name -> sloff.v1.CacheRecord.Input.ResolvedVersion
	5, // 6: sloff.v1.CacheRecord.Output.files:type_name -> sloff.v1.CacheRecord.FileEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sloff_v1_cache_proto_init() }
func file_sloff_v1_cache_proto_init() {
	if File_sloff_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sloff_v1_cache_proto_rawDesc), len(file_sloff_v1_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sloff_v1_cache_proto_goTypes,
		DependencyIndexes: file_sloff_v1_cache_proto_depIdxs,
		EnumInfos:         file_sloff_v1_cache_proto_enumTypes,
		MessageInfos:      file_sloff_v1_cache_proto_msgTypes,
	}.Build()
	File_sloff_v1_cache_proto = out.File
	file_sloff_v1_cache_proto_goTypes = nil
	file_sloff_v1_cache_proto_depIdxs = nil
}
