// Package aqua implements preflight.Checker for the aqua distribution channel.
//
// It compares the packages declared in aqua.yaml against aqua-checksums.json, which is
// regenerated by `aqua install`. Discrepancies indicate that the developer updated
// aqua.yaml without re-running install, which would otherwise let lazygen write a
// "lying" cache record (computed from the new version while the old binary actually ran).
package aqua

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/izumin5210/lazygen/internal/lazygen/preflight"
	resolveraqua "github.com/izumin5210/lazygen/internal/lazygen/toolresolver/aqua"
)

// Name is the checker identifier (matches the resolver Name).
const Name = "aqua"

// ChecksumsFileName is the file aqua install regenerates at the repo root.
const ChecksumsFileName = "aqua-checksums.json"

// Checker validates aqua install state.
type Checker struct {
	repoRoot string
	cfg      *resolveraqua.Config
}

// New loads aqua.yaml from repoRoot and returns a Checker.
func New(repoRoot string) (*Checker, error) {
	cfg, err := resolveraqua.LoadConfig(repoRoot)
	if err != nil {
		return nil, err
	}
	return &Checker{repoRoot: repoRoot, cfg: cfg}, nil
}

// Name implements preflight.Checker.
func (c *Checker) Name() string { return Name }

// Check verifies that every aqua.yaml package has a matching entry in aqua-checksums.json.
// A missing checksums file or unmatched package becomes one Issue with suggestion
// "aqua install".
func (c *Checker) Check(_ context.Context, _ string) (preflight.Result, error) {
	path := filepath.Join(c.repoRoot, ChecksumsFileName)
	b, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return preflight.Result{
			OK: false,
			Issues: []preflight.Issue{{
				Channel:    Name,
				Detail:     fmt.Sprintf("%s が見つかりません (aqua install 未実行?)", ChecksumsFileName),
				Suggestion: "aqua install",
			}},
		}, nil
	}
	if err != nil {
		return preflight.Result{}, fmt.Errorf("read %s: %w", ChecksumsFileName, err)
	}

	var doc checksumsDoc
	if err := json.Unmarshal(b, &doc); err != nil {
		return preflight.Result{}, fmt.Errorf("parse %s: %w", ChecksumsFileName, err)
	}

	var issues []preflight.Issue
	for _, p := range c.cfg.Packages {
		if !doc.matches(p.Name, p.Version) {
			issues = append(issues, preflight.Issue{
				Channel:    Name,
				Detail:     fmt.Sprintf("%s@%s に対応する checksums エントリが見つかりません", p.Name, p.Version),
				Suggestion: "aqua install",
			})
		}
	}
	return preflight.Result{OK: len(issues) == 0, Issues: issues}, nil
}

type checksumsDoc struct {
	Checksums []checksumEntry `json:"checksums"`
}

type checksumEntry struct {
	ID string `json:"id"`
}

// matches uses a substring heuristic — both the package name and version must appear in
// some entry's id. This is loose (could false-positive across similarly-named packages)
// but is good enough for MVP and keeps us out of the business of modelling aqua's full
// per-package-type id format. Tightening this is tracked as an Open Question.
func (d *checksumsDoc) matches(name, version string) bool {
	for _, e := range d.Checksums {
		if strings.Contains(e.ID, name) && strings.Contains(e.ID, version) {
			return true
		}
	}
	return false
}
