// Package pnpmlocal implements toolresolver.Resolver for pnpm workspace-local
// tools. A "tool" here is a workspace package (referenced via "workspace:*"
// in pnpm-lock.yaml); the resolver computes its fingerprint contribution along the
// same axes the spec already has:
//
//   - ExtraInputs (files_hash channel): every file inside the package's dir
//     that git tracks, plus every file inside transitively-linked workspace
//     dirs. .gitignore'd paths (typically dist/, build/, etc.) are excluded.
//     Source edits flip files_hash so consumer tasks rerun the cmd, which
//     itself is responsible for any rebuild step (ADR-0008 D7, mirroring the
//     `go run` model used by go-local).
//   - Versions (resolved_versions_hash channel): every transitively-reachable external
//     npm package, surgically walked from pnpm-lock.yaml's importers and
//     snapshots. Each entry is encoded as `pnpm-deps:<pkg>@<version>` so peer
//     suffixes round-trip and resolved_versions_hash flips on registry-resolved bumps
//     (Turborepo-equivalent precision).
//
// External npm packages used as tools — i.e. anything not in the workspace —
// are out of scope per ADR-0007 and go through the script resolver instead.
//
// Per ADR-0005 the resolver is declared-only: it runs when a task's
// `tools: [name]` list resolves to a tool whose definition is
// `pnpm-local: <package-name>` and the package name is registered as a
// workspace member.
package pnpmlocal

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"sort"
	"sync"

	"github.com/izumin5210/sloff/internal/sloff/toolresolver"
)

// Name is the resolver identifier referenced by spec tools[] entries.
const Name = "pnpm-local"

// DepsPrefix is the version-string prefix for transitive external npm
// dependency entries. Mirrors go-deps used by the go-local resolver so both
// channels expose a uniform "<channel>-deps:<pkg>@<version>" shape on the
// Result.Versions side regardless of language.
const DepsPrefix = "pnpm-deps:"

// Resolver resolves a pnpm workspace-local tool's contributions: source files
// (via FileEnumerator) as ExtraInputs and transitive npm deps as
// pnpm-deps ResolvedVersions. The resolver itself does NOT orchestrate the
// workspace package's build — that's the consuming task's cmd's job. It also
// does NOT validate that node_modules matches pnpm-lock.yaml; that lives in
// the preflight subsystem (preflight/pnpmlocal/) so the runner can apply the
// shared SLOFF_ALLOW_STALE_DEPS read-only escape hatch uniformly.
type Resolver struct {
	repoRoot   string
	enumerator FileEnumerator

	// workspace caches the loaded Workspace snapshot. The initial load is
	// triggered lazily on the first compute call. On an ErrNotWorkspacePackage
	// miss the resolver reloads the workspace once to pick up packages whose
	// package.json was generated by a depends task (ADR-0019 D4). wsMu protects
	// all workspace fields.
	wsMu         sync.Mutex
	workspace    *Workspace
	workspaceErr error

	// pkgs caches the (extra inputs, versions) pair per declared package name
	// so Inputs and Versions don't both walk the lockfile and call the file
	// enumerator. Only successful computations are cached; errors are not, so
	// the ADR-0019 D4 deferred retry can succeed after the depends task runs.
	pkgsMu sync.Mutex
	pkgs   map[string]*pkgComputation
}

// pkgComputation is the memoised result of WalkDeps + collectFiles for one
// declared package name. Both Inputs and Versions read from the same value,
// so the heavy work happens at most once per (resolver, package) per run.
//
// Errors are intentionally not cached: a transient failure (e.g. the workspace
// package does not exist yet because the depends task has not run) must be
// retried on the next call. This is the per-package analogue of the success-only
// caching policy in lister.Memoized (ADR-0019 D4 retry requirement).
//
// Concurrent callers are serialised by mu so that only one goroutine computes
// for a given package at a time; a waiting goroutine will re-check done after
// acquiring the lock and skip the computation if a previous caller succeeded.
type pkgComputation struct {
	mu       sync.Mutex
	done     bool // true only after a successful computation
	inputs   []string
	versions []toolresolver.ResolvedVersion
}

// New constructs a Resolver. The pnpm-lock.yaml is loaded lazily on the first
// Resolve call so sloff runs without a pnpm workspace (Go-only repos)
// don't pay the cost or fail at startup. Pass GitLsFiles for the production
// enumerator; tests inject a fake to avoid a real git working tree.
//
// Install-state drift detection (pnpm-lock.yaml vs node_modules/.pnpm/lock.yaml)
// lives in preflight/pnpmlocal/, not here, so it inherits the shared
// preflight scoping and SLOFF_ALLOW_STALE_DEPS escape-hatch behaviour.
func New(repoRoot string, enumerator FileEnumerator) (*Resolver, error) {
	if enumerator == nil {
		return nil, errors.New("pnpm-local: file enumerator is required")
	}
	return &Resolver{repoRoot: repoRoot, enumerator: enumerator}, nil
}

// Name implements toolresolver.Resolver.
func (r *Resolver) Name() string { return Name }

// Inputs returns the union of git-tracked / non-ignored files inside the
// declared workspace package and every transitively-linked workspace dir,
// repo-relative slash form. The runner folds these into the consuming
// task's input set so source edits flip files_hash and the ADR-0013 overlap
// validation can see upstream codegen producers.
//
// Inputs and Versions share a per-package cache (pkgComputation) so the
// lockfile walk and FileEnumerator invocation happen at most once per
// declared package name per run.
func (r *Resolver) Inputs(ctx context.Context, _ string, declared *toolresolver.DeclaredTool) ([]string, error) {
	pc, err := r.computeFor(ctx, declared)
	if err != nil {
		return nil, err
	}
	return append([]string(nil), pc.inputs...), nil
}

// Versions returns one ResolvedVersion per transitively-reachable external npm
// package, encoded as `pnpm-deps:<pkg>@<version>` so peer suffixes round-trip
// and resolved_versions_hash flips on registry-resolved bumps.
func (r *Resolver) Versions(ctx context.Context, _ string, declared *toolresolver.DeclaredTool) ([]toolresolver.ResolvedVersion, error) {
	pc, err := r.computeFor(ctx, declared)
	if err != nil {
		return nil, err
	}
	return append([]toolresolver.ResolvedVersion(nil), pc.versions...), nil
}

// computeFor returns the per-package cached computation (workspace files +
// external deps) for declared.PackageName. The first successful caller pays
// the lockfile walk and file enumeration; subsequent callers read from memory.
// Failed attempts are not cached so that the ADR-0019 D4 deferred retry can
// succeed once the depends task has generated the package.
func (r *Resolver) computeFor(ctx context.Context, declared *toolresolver.DeclaredTool) (*pkgComputation, error) {
	if declared == nil {
		return nil, errors.New("pnpm-local: declared tool is required (auto-dispatch was removed in ADR-0005)")
	}
	if declared.PackageName == "" {
		return nil, errors.New("pnpm-local: declared package name is required")
	}
	pc := r.pkgComputationFor(declared.PackageName)

	pc.mu.Lock()
	defer pc.mu.Unlock()

	if pc.done {
		return pc, nil
	}
	inputs, versions, err := r.compute(ctx, declared.PackageName)
	if err != nil {
		return nil, err
	}
	pc.inputs = inputs
	pc.versions = versions
	pc.done = true
	return pc, nil
}

func (r *Resolver) pkgComputationFor(packageName string) *pkgComputation {
	r.pkgsMu.Lock()
	defer r.pkgsMu.Unlock()
	if r.pkgs == nil {
		r.pkgs = map[string]*pkgComputation{}
	}
	if existing, ok := r.pkgs[packageName]; ok {
		return existing
	}
	pc := &pkgComputation{}
	r.pkgs[packageName] = pc
	return pc
}

// compute walks the lockfile from packageName's importer entry, gathering
// the workspace dirs (via link: edges) and transitive external npm deps
// (via snapshots), then runs the FileEnumerator for the union of workspace
// dirs. The result feeds both Inputs (workspace files) and Versions (npm
// dep entries).
//
// On an ErrNotWorkspacePackage miss, compute reloads the workspace once before
// giving up. This lets the ADR-0019 D4 deferred retry succeed after a depends
// task has generated the package's package.json, without paying a re-read on
// every happy-path call.
func (r *Resolver) compute(ctx context.Context, packageName string) ([]string, []toolresolver.ResolvedVersion, error) {
	ws, err := r.loadWorkspace()
	if err != nil {
		return nil, nil, fmt.Errorf("pnpm-local: load workspace: %w", err)
	}
	pkg, ok := ws.Lookup(packageName)
	if !ok {
		// Package absent from the cached snapshot. Try a fresh workspace load
		// in case the depends task just generated the package.json; only one
		// reload is attempted per compute call to avoid runaway re-reads.
		fresh, reloadErr := r.reloadWorkspace()
		if reloadErr != nil {
			// Reload itself failed; surface the original miss.
			return nil, nil, fmt.Errorf("%w: %q", ErrNotWorkspacePackage, packageName)
		}
		pkg, ok = fresh.Lookup(packageName)
		if !ok {
			return nil, nil, fmt.Errorf("%w: %q", ErrNotWorkspacePackage, packageName)
		}
	}

	walk, err := WalkDeps(ws.lockfile, filepath.ToSlash(pkg.Dir))
	if err != nil {
		return nil, nil, fmt.Errorf("pnpm-local: walk deps for %q: %w", pkg.Name, err)
	}

	extraInputs, err := r.collectFiles(ctx, walk.Workspaces)
	if err != nil {
		return nil, nil, fmt.Errorf("pnpm-local: enumerate files for %q: %w", pkg.Name, err)
	}

	versions := make([]toolresolver.ResolvedVersion, 0, len(walk.Externals))
	source := Name + ":" + pkg.Name
	for _, e := range walk.Externals {
		versions = append(versions, toolresolver.ResolvedVersion{
			Name:    e,
			Source:  source,
			Version: DepsPrefix + e,
		})
	}
	return extraInputs, versions, nil
}

// loadWorkspace returns the cached Workspace, loading it on first call.
// Concurrent callers are serialised by wsMu. On success the workspace is
// cached for the lifetime of the resolver (happy-path is zero-cost); on
// error the failure is also cached so repeated lookups don't re-hit the
// filesystem for the same broken state. A deliberate reload (for the
// ADR-0019 D4 retry) goes through reloadWorkspace instead.
func (r *Resolver) loadWorkspace() (*Workspace, error) {
	r.wsMu.Lock()
	defer r.wsMu.Unlock()
	if r.workspace != nil || r.workspaceErr != nil {
		return r.workspace, r.workspaceErr
	}
	r.workspace, r.workspaceErr = LoadWorkspace(r.repoRoot)
	return r.workspace, r.workspaceErr
}

// reloadWorkspace discards the cached snapshot and loads a fresh one.
// It is called only from the ErrNotWorkspacePackage retry path in compute,
// so that a package generated by a depends task becomes visible to the
// ADR-0019 D4 deferred retry without paying a re-read on every happy-path call.
func (r *Resolver) reloadWorkspace() (*Workspace, error) {
	r.wsMu.Lock()
	defer r.wsMu.Unlock()
	ws, err := LoadWorkspace(r.repoRoot)
	if err != nil {
		// Preserve the cached workspace if the reload itself fails; the original
		// (possibly partial) snapshot is better than nothing for other packages.
		return nil, err
	}
	r.workspace = ws
	r.workspaceErr = nil
	return ws, nil
}

// collectFiles enumerates every file across all of the package's workspace
// dirs in a single enumerator call and returns the deduplicated, sorted union
// as repo-relative slash-form paths suitable for the runner's input merge.
// Batching every dir into one call (rather than one per dir) keeps the
// production enumerator to a single `git ls-files` subprocess regardless of
// how many workspace packages the tool transitively links.
func (r *Resolver) collectFiles(ctx context.Context, workspaceDirs []string) ([]string, error) {
	if len(workspaceDirs) == 0 {
		return nil, nil
	}

	osDirs := make([]string, 0, len(workspaceDirs))
	for _, slashDir := range workspaceDirs {
		osDirs = append(osDirs, filepath.FromSlash(slashDir))
	}

	files, err := r.enumerator(ctx, r.repoRoot, osDirs...)
	if err != nil {
		return nil, fmt.Errorf("enumerate %d workspace dir(s): %w", len(osDirs), err)
	}

	seen := make(map[string]struct{}, len(files))
	out := make([]string, 0, len(files))
	for _, f := range files {
		s := filepath.ToSlash(f)
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	sort.Strings(out)
	return out, nil
}
