name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - name: build
            run: go build -v ./cmd/sloff
          - name: fix
            run: go fix -v ./...
          - name: format
            run: go tool gofumpt -l -w -- .
          - name: lint
            run: go vet -v ./...
          - name: tidy
            run: go mod tidy
          - name: proto-generate
            run: go tool buf generate
          - name: proto-lint
            run: go tool buf lint
          - name: proto-breaking
            run: go tool buf breaking --against '.git#branch=main'
      fail-fast: false
    permissions:
      contents: read
    name: ${{ matrix.command.name }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: ${{ matrix.command.name == 'proto-breaking' && 0 || 1 }}
    - uses: actions/setup-go@v6
      with:
        go-version: '1.26'
    - name: ${{ matrix.command.name }}
      run: ${{ matrix.command.run }}
    - name: Check for uncommitted changes
      run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
      - uses: k1LoW/octocov-action@v1

  status-check:
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
